name: Workflow

on: 
  pull_request:
    branches: [ dev ]

jobs:

  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code 
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cacha: maven
    - name: Build with Maven account service
      run: mvn -B clean package --file account-service/pom.xml
    - name: Build with Maven transaction service
      run: mvn -B clean package --file transaction-service/pom.xml 
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Build and push account service
      id: account-service-docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./account-service
        file: ./account-service/Dockerfile
        push: true
        tags:  karabulutserkan/account-service:latest  
    - name: Build and push transaction service
      id: transaction-service-docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./transaction-service
        file: ./transaction-service/Dockerfile
        push: true
        tags:  karabulutserkan/transaction-service:latest
    - name: Build and push frontend
      id: frontend-docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags:  karabulutserkan/frontend:latest