name: Workflow

on: 
  pull_request:
    branches: [ dev ]

jobs:

  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code 
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        cacha: maven
    - name: Build with Maven account service
      run: mvn -B clean package --file account-service/pom.xml
    - name: Build with Maven transaction service
      run: mvn -B clean package --file transaction-service/pom.xml 